shared:
  image: golang
  environment:
    GOPATH: /sd/workspace

jobs:
  main:
    requires: 
      - ~pr
      - ~commit
    steps:
      - get: go get -t ./...
      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
      - test: go test ./...
      - build: go build ./...
